### ISSUE TITLE
free vs new

### ISSUE THREAD

**Issue by rurban** [FastFilter/fastfilter_cpp#16]
https://github.com/FastFilter/fastfilter_cpp/blob/677b2907d094489774c5f88df8b057b9a0a3d2d2/src/bloom/bloom.h#L299

rather use delete[] here.
g++-11 warns with../src/bloom/bloom.h:299:7: warning: 'void free(void*)' called on pointer returned from a mismatched allocation function [-Wmismatched-new-delete]
  299 |   free(data);

**Comment by lemire** [comment]
You are correct, I believe.
