### ISSUE TITLE
Reorganize the code: use SimpleMixSplit instead of TwoIndependentMultiplyShift

### ISSUE THREAD

**Issue by thomasmueller** [FastFilter/fastfilter_cpp#18]
It's a bit hard to integrate more algorithms currently.
I would like to add the ribbon filter for example, and maybe more will be added later.
I will try to re-organize the code a bit.

**Comment by thomasmueller** [comment]
Sometimes we use TwoIndependentMultiplyShift; we should probably use SimpleMixSplit consistently.

**Comment by lemire** [comment]
> Sometimes we use TwoIndependentMultiplyShift; we should probably use SimpleMixSplit consistently.

Yes. I agree.

**Comment by thomasmueller** [comment]
I included some more changed I had in my working directory... I hope it still works.
I want to change some more stuff.
