### ISSUE TITLE
Question on block Bloom filter sizing

### ISSUE THREAD

**Issue by mavam** [FastFilter/fastfilter_cpp#24]
I've been looking at the implementation of the (fixed) blocked Bloom filters, which can be constructed by specifying a number of bits. The benchmark factory invokes the constructors with an `add_count` parameter that signifies the capacity, i.e., number of supported items.

How does the capacity in items translate to bits as `ceil(add_count * 8.0 / CHAR_BIT)`?

I'm referring, e.g., to the specialization of `FilterAPI<SimdBlockFilterFixed<HashFamily>>` in `filterapi.h`:

```cpp
  static Table ConstructFromAddCount(size_t add_count) {
    Table ans(ceil(add_count * 8.0 / CHAR_BIT));
    return ans;
  }
```

**Comment by lemire** [comment]
I am also not sure what this code tries to do. But `ceil(add_count * 8.0 / CHAR_BIT)` is likely always `add_count` since `CHAR_BIT` is 8.

**Comment by thomasmueller** [comment]
It doesn't look useful here.

It looks like this originally comes from https://github.com/efficient/cuckoofilter/blame/master/benchmarks/bulk-insert-and-query.cc  - here https://github.com/efficient/cuckoofilter/commit/f523b160ef32d2a83f1fd16bf4fb0c1b65620c5d - notice the log2 here. And then (by mistake) we copied it over to other implementations for no good reason.

Feel free to change it!

**Comment by mavam** [comment]
So the question is: what would be a reasonable function that computes *m*, the number of bits, from *n*, *p*, and *k*? Given that we're dealing with a split block Bloom filter here, we need to use this approximation from the [blocked Bloom filter paper](http://algo2.iti.kit.edu/singler/publications/cacheefficientbloomfilters-wea2007.pdf):

![image](https://user-images.githubusercontent.com/53797/136080217-ae02fbaa-0bae-49bb-93bf-2f03fbf58b12.png)

We have *k = 8* and *B = 256* due to the SIMD multiply-shift universal hashing. Based on comments in your implementation, it looks like you found that *c = 24* gives optimal results for a fixed *p*.

What remains to do is to find some function that translates the inputs to *n* and *p* numerically to *m*, right?
