### ISSUE TITLE
Clean out rejected experiments

### ISSUE THREAD

**Issue by lemire** [FastFilter/fastfilter_cpp#3]
There is lots and lots of dead code in this repository. It is confusing to people who are not familiar with the project.

I think that only the "good" implementations should be kept in master.

Failed experiments could go into branches.

**Comment by thomasmueller** [comment]
I agree. I will work on this.

**Comment by thomasmueller** [comment]
This should finally be complete.

**Comment by thomasmueller** [comment]
Well at least the "right" algorithms are now run by default... I still should clean up (actually remove) old algorithms at some point...
