### ISSUE TITLE
block bloom filter implementation details (questions)

### ISSUE THREAD

**Issue by patelprateek** [FastFilter/fastfilter_cpp#31]
Thanks for this work.
new to this field so please bear with some naive questions .

Is there a difference between the blockedbloom implementation here vs the split block bloom filter here conceptually : https://github.com/jbapple/libfilter/blob/0b13e231a9dbfedf396bc151c7bb03ea592c4858/c/include/filter/block.h

trying to understand when should i use split block BF vs block BF , if you can provide any guidance that will be helpful

Also when running few benchmarks , i observe optimal bits per value different than bits per value , why does this happen ?
I also observed my false positive error rate remains the same in the benchmark irrespective of number of values/keys inserted for all the filters , is this because we are increasing the size of filters to maintain the false positive rate by keeping the bits per value constant. ?

My use case is inserting about 1M- 100M keys within range [0-100M]

**Comment by lemire** [comment]
> i observe optimal bits per value different than bits per value , why does this happen ?

Because we are not using filters with optimal space usage.

**Comment by thomasmueller** [comment]
> Is there a difference between the blockedbloom implementation here vs the split block bloom filter here conceptually 

I'm not aware of a difference, except for the name. Jim Apple used the name "split block Bloom filter" in his paper, https://arxiv.org/abs/2109.01947 and we use the (shorter) name "blocked Bloom". But I believe the implementation is essentially the same (except for renaming things a bit):

https://github.com/FastFilter/fastfilter_cpp/blob/master/src/bloom/simd-block-fixed-fpp.h#L181
https://github.com/jbapple/libfilter/blob/master/c/include/filter/block.h#L183
